### ISSUE TITLE
Error about mkdir collision when destination folder already exists.

### ISSUE THREAD

**Issue by kauffy** [get-got/discord-downloader-go#114]
When I launch DDG now, I get a continually recurring error like the one below. Its complaint is that the destination folder already exists-- but this shouldn't be an error condition. Obviously, it should just ignore this fact and proceed as if it had created it.
```Error while creating subfolder "D:\Workspace_Safe\Discord\Midjourney\Text Channels glass\images\": mkdir D:\Workspace_Safe\Discord\Midjourney\Text Channels glass\images\: Cannot create a file when that file already exists.```

**Comment by kauffy** [comment]
I guess divideByChannel has been deprecated. If entirely so, then you can close this one.

**Comment by get-got** [comment]
Thank you, I had started a reply the other day that I didn't end up finishing, I was very confused how you could be getting that error since logically that wouldn't make sense with this:

![image](https://github.com/get-got/discord-downloader-go/assets/43052079/843d5f36-281d-444d-80ad-f51a5366dc9e)

But it being a shortcut makes a whole lot more sense. I'll make note of this and see if I can account for shortcuts soon. I'll reply here when I do.

**Comment by kauffy** [comment]
It's probably very much an edge case.
