### ISSUE TITLE
watchSettings not honored?

### ISSUE THREAD

**Issue by kauffy** [get-got/discord-downloader-go#115]
I have watchSettings set to true, but it appears that it has no effect; changing the settings file isn't apparently affecting the running application.

**Comment by get-got** [comment]
I just tested and it works fine for me, could it possibly be due to shortcuts like your other issue?

**Comment by kauffy** [comment]
To make sure I understand the intended function, any change that I make to the settings.json file should trigger the running program to reread its settings and then operate from the new settings, correct?

In my case, if I make a change to settings, it is reflected in the running application in no way. The settings file is in the same directory as the executable, and neither is shortcuted, so I'm not sure where the disconnect is.

For extra compatibility, I threw out my old settings file and used your new version as a template, and then filled in the appropriate settings.
----------------------------------------

Nov 30, 2023 17:12:59 DRN ***@***.***>:

**Comment by kauffy** [comment]
I just checked to verify that this is the case, and it definitively does not reload.

**Comment by get-got** [comment]
Unless you have some weird specific issue, I think I just found what's happening.

I'm assuming by "changing the settings file" in your case, you mean copying/moving a settings.json file from elsewhere into the bot folder, overwriting the existing file that the bot loaded with? If so, that seems to not result in a reload and additionally completely breaks the functionality of the filesystem watcher until reload.

The utility behind watchSettings binds to that specific file at the time of load, not the filepath, because that utility (https://github.com/fsnotify/fsnotify) was made to also track file renaming and deletion for other purposes. So if you replace the original file, it considers the new settings.json a separate file and doesn't watch it. It's only watching for modifications to the existing file that was loaded, so it should update fine if you **edit** the file in a text editor.

If that's what's happening here, I can add an additional watchSettings option to try and catch it (additional because the solution I have in mind reportedly causes a lot of misfires from certain programs indexing files in the background).

**Comment by kauffy** [comment]
Well.... I'm not bringing anything in; I'm editing the settings.json in place.

**Comment by get-got** [comment]
I really have no idea what could be causing this... I haven't had anyone report this before and your environment sounds normal.

What text editor are you using? Maybe it's somehow interfering.

**Comment by kauffy** [comment]
Just as a reminder, this still doesn't do its thing for me.

**Comment by get-got** [comment]
I can't fix this if I can't replicate it, I haven't been able to figure out any scenario that causes it to not work for me, it always works. Nobody else has ever reported this issue so I have no idea what to try.

**Comment by kauffy** [comment]
Well, that triggered a thought, and I investigated it. I have been using UltraEdit, which is a regular ol' text editor except (it appears), it must be saving the original file as the backup (renaming it) and saving to a new file. When I edited in n++, ddg picked it up.

**Comment by get-got** [comment]
That'll do it. The watchSettings feature binds to the specific file. If it's moved the connection will break even if it's the same path. This seems like a unique issue for that text editor, like I said nobody else has reported and I tried like 4 different editors when you first reported this, they all worked.

**Comment by kauffy** [comment]
It only occurred to me just now when you described how the process works above-- UE could be doing something weird with the backup file.
