### ISSUE TITLE
"Failed to convert timestamp to discord snowflake..." message.

### ISSUE THREAD

**Issue by kauffy** [get-got/discord-downloader-go#118]
Not sure if this is of interest, or not, but upon starting, I get a few of these messages:

```Failed to convert timestamp to discord snowflake... Format: '2023-10-31', Timestamp: '2006-01-02' - Error:    parsing time "2006-01-02" as "2023-10-31": cannot parse "-01-02" as "3"```

The filenameDateFormat was left as the default: ```"filenameDateFormat": "2006-01-02_15-04-05"```

and I assume the other date it's mashing it with is: ```"autoHistorySince": "2023-10-31"```

**Comment by ajgrasmeijer** [comment]
The function `discordTimestampToSnowflake` in `discord.go` have the variables swapped around.

The fix would be to swap around the function parameters, so that it says:
`func discordTimestampToSnowflake(timestamp string, format string) string {`

My git knowledge is basically nil, so I hope @get-got reads this. :-)

**Comment by get-got** [comment]
@ajgrasmeijer If you meant this section, you were totally right, I had these mistakenly reversed at this location in `history.go`:

![image](https://github.com/get-got/discord-downloader-go/assets/43052079/da67a048-9e09-4686-8d11-7236d8501c41)

Changing the parameter order of the actual function isn't the fix since that would break a lot of other things. I need to undo some recent broken thread fix attempts but once I do, I'll send this in the support discord server to see if anyone can help test the date ranges.
