### ISSUE TITLE
Self-Bot doesn't work

### ISSUE THREAD

**Issue by DrinkMyDepresso** [get-got/discord-downloader-go#15]
I set up the Self-Bot, and typed in a commend. The exe said there was a DM from me to the self bot, but no images were downloaded.

**Comment by get-got** [comment]
Discord seems to have broken something, don't know if it was intentional or not. User accounts (at least with discordgo, I haven't tried any other libraries) don't receive message content data, so it knows things are being sent but has no idea what you're sending it.

If this persists I'll see if I can find a workaround but may not be possible if it's something they did intentionally.


In the meantime, application bots are functioning 100% normally. The only caveat is you can only add it to servers you have admin permissions in.
