### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by PatriamOfficial** [get-got/discord-downloader-go#19]
Config setup is fine, just when I try to launch it I get this error:

2021/05/13 14:14:35.864932 main.go:347: Discord login failed:   websocket: close 4004: Authentication failed.
2021/05/13 14:14:35.867897 common.go:29: Exiting in 15 seconds - uptime was  921 milliseconds 161 microseconds ...

**Comment by get-got** [comment]
@PatriamOfficial Have you used this before or is this your first attempt?

If it previously worked and isn't now, I'm not sure what's wrong and would need more info.

Otherwise, I think there's just something wrong with your token or email/password in the settings. Double check that there's no extra symbols in it that shouldn't be. If using a token for a user account, make sure you have `"userBot": true` in the credentials section.
