### ISSUE TITLE
Feature request - "Image comparison log?"

### ISSUE THREAD

**Issue by Reaper176** [get-got/discord-downloader-go#38]
Don't know if this already exists in some way and I have simply missed it. But when having the program sort out duplicates it gives the score, and what seams to be a link the the file it is comparing but not the file it is being compared too. Would it be possible to have this displayed? If so I would find it exceptionally useful. 

Also could this information be putout to a specific log so that one could manually compare images.

**Comment by get-got** [comment]
Sorry for such a late response, I tweaked DebugOutput so that it outputs score comparisons. Unfortunately, the way the image comparison database works, all it does is store hashes that it compares to, no filenames or anything identifiable, so it's hard to tell what images it's comparing against in the output.

Are you on Windows? If you don't know how to build go projects, I can send you a build with it.

What I would recommend is to gather some very similar images, some almost identical images, and some very different images, and using a blank database see what scores they output and tweak as you want.

``(lowest is around -109.7), Higher = less similar (does not really have a maximum, would require your own testing)``

**Comment by birdofhermes** [comment]
I am not sure if this was already tackled, i am using the following version:
Welcome to discord-downloader-go v1.6.3 
main.go:58: [Version] discord-go v0.22.0 using Discord API v6
But if you attempt to download the same filename twice than it detects as a possible duplicate and does not download anything.
E.g.: upload to a channel that is monitored an "image.jpg" and let the program download it, after its been down upload a totaly different file with the same "image.jpg" name and it will drop:
` downloads.go:953: >>> SKIPPING FILE: Matching filenames, possible duplicate...`

Is this image comparison part making this issue go away? or its something so far noone had?
