### ISSUE TITLE
Bit of a mystery when it comes to building the package.

### ISSUE THREAD

**Issue by carlca** [get-got/discord-downloader-go#4]
I came to this package via the original github.com/Seklfreak/discord-image-downloader-go package, but because I fancied a more actively maintained project and also JSON config files, I went with yours!

Something, I've noticed with both the original package and yours is that neither seems to build from the command-line using `go 1.15.5` under `macOS 10.14.6`. Both bring up module/version errors. Yours gives...
```
go: github.com/Necroforger/dgrouter/examples/soundboard imports
	github.com/rylio/ytdl: github.com/rylio/ytdl@v1.0.4: parsing go.mod:
	module declares its path as: github.com/Andreychik32/ytdl
	        but was required as: github.com/rylio/ytdl
```
This is after the command `go build ...` which, to my understanding, should build everything in the folder.

Yet, if I load `main.go` within VS Code, and choose `Go: Build Workspace` from the command palette, everything builds nicely. 

So, it's not a problem! I can work with the package, and indeed I have already forked it, since I plan to make some changes for my specific task. I just thought it was a strange situation. I've already posted messages on https://forum.golangbridge.org and on Twitter, so we'll see if someone can solve this mystery...

**Comment by get-got** [comment]
That's odd, it seems like it's exclusively due to the soundboard portion of dgrouter (a package I use for commands in the bot), since part of your error involves ytdl, which this program doesn't use, but dgrouter does.

I'm not really sure how to replicate that issue, nor how to fix it, but I'm glad you found a work-around.

If you add anything you think other people could have use for, please make a pull request!
