### ISSUE TITLE
Forums supported?

### ISSUE THREAD

**Issue by Jopo-JP** [get-got/discord-downloader-go#96]
Hi there,

are forums threads supported?

I always get the Error: `BOT DOES NOT HAVE PERMISSION TO READ MESSAGE HISTORY!!!`

The bot does have permission to read the history.
If i try on an other channel with threads, it does work.

Thanks for the cli.

**Comment by get-got** [comment]
@Jopo-JP If you join the Discord @ https://discord.gg/6Z6FJZVaDV and see the General channel, I recently sent some executables for the last commit where I think I fixed/supported threads & forums properly. I haven't pushed a release version since I haven't had confirmation from someone else that it's performing as expected.
